spring.application.name=ProjectManagementSystem

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/projectmanagement
spring.datasource.username=root
spring.datasource.password=asdfghjkl@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true


#//For Controllers in order
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha

#######Configure Email from gmail security and app password
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.username=ssarfrazsahir@gmail.com
spring.mail.password= rbhtavisjnwllmos
spring.mail.properties.mail.setup.auth=true
spring.mail.properties.mail.setup.starttls.enable=true

